### ISSUE TITLE
Isomorphic and SSR ?

### ISSUE THREAD

**Issue by mzgnr** [bigardone/phoenix-trello#8]
I've seen that application contains isomorphic-fetch npm package. Is this application server side rendered ? Am I missing something ?

**Comment by bigardone** [comment]
Hi! thanks for the comment.
It's not server side rendered for now... It's just containing it because I have it in the template I always use for react/redux applications I code, whether they are isomorphic or not.
Being honest, I've never stopped to think about this being an issue.
Shall I use the original https://github.com/github/fetch instead?

**Comment by mzgnr** [comment]
I'm not sure about that. But its a nice phoenix + redux example for my project. Thanks for that by the way.
